import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SelectYearProvider from "@/providers/SelectYearProvider";
import { Spinner } from "@/components/Loader";
import LoaderProvider from "@/providers/LoaderProvider";
import MobileMenuProvider from "@/providers/MobileMenuProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MobileMenuProvider>
      <SelectYearProvider>
        <LoaderProvider>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable}  w-screen overflow-x-hidden md:mt-10`}
            >
              {children}
              <Spinner />
            </body>
          </html>
        </LoaderProvider>
      </SelectYearProvider>
    </MobileMenuProvider>
  );
}
